services:
  app:
    image: kino-in-karlsruhe
    container_name: kino-app
    restart: unless-stopped
    ports:
      - 3001:3000
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/kino-in-karlsruhe
      - TMDB_API_KEY=${TMDB_API_KEY}

  db:
    image: postgres:15
    container_name: kino-postgres
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kino-in-karlsruhe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4
    container_name: kino-pgadmin
    restart: unless-stopped
    ports:
      - 9080:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db

volumes:
  pg_data:
  pgadmin_data:
